### ISSUE TITLE
Horizontal scroll for sub-sub-menus

### ISSUE THREAD

**Issue by dglin** [dglin/SJ-Theming#13]
<img width="198" alt="screen shot 2016-11-03 at 2 16 35 pm" src="https://cloud.githubusercontent.com/assets/13558547/19985508/383a78d8-a1d0-11e6-9b67-1d21f4e0ab66.png"></br>
Have sub-sub-menus show up on mouse hover. Currently need to horizontally scroll in order to view sub-sub-menus which isn't very intuitive.

**Comment by nicholasreynolds** [comment]
Is this still an issue

**Comment by dglin** [comment]
Looks fixed!
