### ISSUE TITLE
nav during scroll down

### ISSUE THREAD

**Issue by dglin** [dglin/SJ-Theming#15]
<img width="737" alt="screen shot 2016-11-03 at 2 26 27 pm" src="https://cloud.githubusercontent.com/assets/13558547/19985798/95bb211e-a1d1-11e6-9723-37885674f687.png">
</br>
Make the navbar more fluid during scroll down. Making the top-bar (with the search and login etc.) stick to the navbar in case of scrolling.

**Comment by saileshpatnala** [comment]
Latest commit makes the topbar stick to the navbar on scroll. What else needs to be done to make scroll smoother?
